export {default as Header} from './Header'
export {default as Nav} from './Nav'
export {default as About} from './About'
export {default as Projects} from './Projects'
export {default as Footer} from './footer'